github: [HisokaLabs, DikaArdnt] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: DikaArdnt # Replace with a single Ko-fi username
custom: ['https://saweria.co/DikaArdnt'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
